// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using estágio.Data;

namespace estágio.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("estágio.Data.entidades", b =>
                {
                    b.Property<string>("nome")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("data")
                        .HasPrecision(8)
                        .HasColumnType("longtext");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.HasKey("nome");

                    b.ToTable("entidade");

                    b.HasData(
                        new
                        {
                            nome = "Consertar carro",
                            data = "01/04/2002",
                            status = "concluido"
                        },
                        new
                        {
                            nome = "Cortar grama",
                            data = "03/04/2002",
                            status = "Em processo"
                        },
                        new
                        {
                            nome = "Montar computador",
                            data = "2/04/2002",
                            status = "Em processo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
